name: Merge master into all branches

on:
  push:
    branches:
      - master


jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all branches
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Merge changes into other branches
        id: merge
        run: |
          git config user.name "dev3fyfy"
          git config user.email "dev.ahmed.afifi@gmail.com"
          conflicts=""

          pull_request_url=""
          for branch in $(git ls-remote --heads origin | awk -F'/' '{print $3}'); do
            if [ "$branch" != "master" ]; then
              git checkout "$branch"
              git merge --no-commit --no-ff --no-edit origin/master || {
                git merge --abort
                conflicts+=("$branch")
                echo "Creating pull request for $branch"
                response=$(curl --request POST \
                  --url https://api.github.com/repos/$GITHUB_REPOSITORY/pulls \
                  --header 'authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}' \
                  --header 'content-type: application/json' \
                  --data '{
                    "title": "Merge master into '"$branch"' (auto) ${GITHUB_SHA::8}",
                    "body": "There were merge conflicts when attempting to merge changes from  into this branch. Please resolve the conflicts and merge the changes manually.",
                    "head": "master",
                    "base": "'"$branch"'"
                  }')
                echo "$response"
                echo "pull_request_url $(echo "$response" | jq -r '.html_url')"
                pull_request_url+=$(echo "$response" | jq -r '.html_url')
                curl -X POST -H 'Content-type: application/json' \
                --data '{"text":"Hello, world!"}' \
                https://hooks.slack.com/services/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

              }
              if [ -z "$(git status --porcelain)" ]; then
                git push origin "$branch"
              else
                git commit -am "Merge branch 'master' into $branch"
                git push origin "$branch"
              fi
            fi
          done
          if [ ${#conflicts[@]} -gt 0 ]; then
            echo "Merge conflicts occurred in the following branches: ${conflicts[@]} \n ${pull_request_url[@]}"
          else
            echo "No merge conflicts occurred."
          fi
