name: Merge master into all branches

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all branches
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Merge changes into other branches
        run: |
          git config user.name "dev3fyfy"
          git config user.email "dev.ahmed.afifi@gmail.com"
          conflicts=""
          for branch in $(git ls-remote --heads origin | awk -F'/' '{print $3}'); do
            if [ "$branch" != "master" ]; then
             git checkout "$branch"
              git merge --no-ff --no-edit origin/master
              if [ $? -ne 0 ]; then
                conflicts=$((conflicts+1))
                git push --force origin "$branch"
                pull_request_title="Merge conflicts from 'master' into '$branch'"
                pull_request_body="This pull request resolves conflicts between the 'master' branch and the '$branch' branch."
                pull_request_url=$(curl --silent --request POST \
                  --url https://api.github.com/repos/$GITHUB_REPOSITORY/pulls \
                  --header "authorization: Bearer $GITHUB_TOKEN" \
                  --header 'content-type: application/json' \
                  --data "{\"title\":\"$pull_request_title\",\"body\":\"$pull_request_body\",\"head\":\"$branch\",\"base\":\"master\"}" \
                  | jq -r '.html_url')
                pull_requests="$pull_requests\n- <$pull_request_url|$pull_request_title>"
              else
                git push origin "$branch"
              fi
            fi
          done
          if [ -n "$conflicts" ]; then
            echo "Merge conflicts occurred in the following branches:$conflicts"
          else
            echo "No merge conflicts occurred."
          fi
