name: Merge master into all branches

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all branches
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Merge changes into other branches
        run: |
          git config user.name "dev3fyfy"
          git config user.email "dev.ahmed.afifi@gmail.com"
          echo "$(git ls-remote --heads origin | awk -F'/' '{print $3}')"
          for branch in $(git ls-remote --heads origin | awk -F'/' '{print $3}'); do              echo "$branch"
            if [ "$branch" != "master" ]; then
              echo "$branch"
              git checkout "$branch"
              git merge --no-ff --no-edit origin/master
              git push origin "$branch"
            fi
          done
