name: Compare Commit with Staging Branch
on:
  pull_request:
    branches:
      - master

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all branches
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: print diff
      run: |
          git config user.name "dev3fyfy"
          git config user.email "dev.ahmed.afifi@gmail.com"
          git fetch origin staging
          git diff --name-only origin/staging..HEAD > mydiff
          echo "staging = "
          cat mydiff
          git fetch origin add-app-spec
          git merge --no-commit --no-ff --no-edit  --allow-unrelated-histories  origin/add-app-spec > mydiff
          echo "same-master add-app-spec = "
          cat mydiff
          git fetch origin master2
          git merge --no-commit --no-ff --no-edit  --allow-unrelated-histories  origin/master2 > mydiff
          echo "same-master master2 = "
          git merge --no-commit --no-ff --no-edit --allow-unrelated-histories origin/master3 > mydiff
          cat mydiff


