name: Compare Commit with Staging Branch
on:
  pull_request:
    branches:
      - master

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: print diff
      run: |
          git fetch origin staging
          git diff --name-only origin/staging..HEAD > mydiff
          echo "staging = "
          cat mydiff
          git fetch origin add-app-spec
          git diff --name-only origin/add-app-spec..HEAD > mydiff
          echo "same-master add-app-spec = "
          cat mydiff
          git fetch origin master2
          git diff --name-only origin/master2..HEAD > mydiff
          echo "same-master master2 = "

          git merge --no-commit --no-ff --no-edit origin/staging
          cat mydiff


