name: Compare Commit with Staging Branch
on:
  pull_request:
    branches:
      - master

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # fetch all history for all branches
        token: ${{ secrets.PERSONAL_TOKEN }}
        
    - name: Set env.BRANCH
      run: |
          echo $GITHUB_REF
          echo "BRANCH=$(echo $GITHUB_REF | sed "s/refs\/heads\///")" >> $GITHUB_ENV
          echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "test=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
    - name: print diff
      run: |
          git config user.name "dev3fyfy"
          git config user.email "dev.ahmed.afifi@gmail.com"
          echo "same-master master2 = "
          git checkout origin/master3
          git merge  origin/${{ env.BRANCH }} > mydiff
          cat mydiff



# git fetch origin add-app-spec
# git merge --no-commit --no-ff --no-edit  --allow-unrelated-histories  origin/add-app-spec > mydiff
# echo "same-master add-app-spec = "
# cat mydiff
# git fetch origin master2
# git merge --no-commit --no-ff --no-edit  --allow-unrelated-histories  origin/master2 > mydiff

