name: Compare Commit with Staging Branch
on:
  push:
    branches:
      - dev3fyfy-patch-3

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: print diff
      run: |
          git fetch origin staging
          git diff origin/staging..HEAD > mydiff
          echo "mydiff = "
          cat mydiff
