name: Compare Commit with Staging Branch
on:
  pull_request:
    branches:
      - master

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: print diff
      run: |
          git fetch origin staging
          git diff origin/staging..HEAD > mydiff
          echo "staging = "
          cat mydiff
          git fetch origin add-app-spec
          git diff origin/add-app-spec..HEAD > mydiff
          echo "same-master add-app-spec = "
          cat mydiff


