name: Compare Commit with Staging Branch
on:
  push:
    branches:
      - dev3fyfy-patch-3

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Last Pull Request Number
      run: echo "$(curl -s "https://api.github.com/repos/:owner/:repo/pulls?state=all&sort=created&direction=desc&page=1&per_page=1" )"
    - name: Get Last Pull Request Number
      run: echo "::set-output name=pull_request_number::$(curl -s "https://api.github.com/repos/:owner/:repo/pulls?state=all&sort=created&direction=desc&page=1&per_page=1" | jq -r '.[0].number')"
    - name: Use Pull Request Number
      run: echo "The last pull request number is ${{ steps.compare-commit-with-staging.outputs.pull_request_number }}."      
    - name: Get Last Commit SHA
      run: echo "::set-output name=last_commit_sha::$(curl -s https://api.github.com/repos/:owner/:repo/pulls/:${{ steps.get-last-pull-request-number.outputs.pull_request_number }} | jq -r '.merge_commit_sha')"
    - name: Use Last Commit SHA
      run: git diff ${{ steps.compare-commit-with-staging.outputs.last_commit_sha }} HEAD~
