name: Compare Commit with Staging Branch
on:
  push:
    branches:
      - dev3fyfy-patch-3

jobs:
  compare-commit-with-staging:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get Last Pull Request Number
      run: echo "$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=all&sort=created&direction=desc&page=1&per_page=1" )"
    - name: Get Last Commit SHA
      run: echo "::set-output name=last_commit_sha::$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=all&sort=created&direction=desc&page=1&per_page=1" | jq -r '.[0].merge_commit_sha')"
    - name: Use Last Commit SHA
      run: |
         git diff  ${GITHUB_REF}  staging
